#IF YOURE WONDERING WHERE ALL THE NON-CONSCRIPT JOBS WENT
#JUST RE-ENABLE THEM AND SET editorHidden: false
#YOU'RE WELCOME
# .2 - 2025

- type: department
  id: Logistics
  description: department-Cargo-description
  color: "#A46106"
  weight: -90
  primary: false
  editorHidden: true

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: 5
  editorHidden: false

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - CentralCommandOfficial
  - HeadOfPersonnel # Not shown but needed here for playtime
  - HeadOfSecurity # Not shown but needed here for playtime
#  - ChiefMedicalOfficer
  primary: false
  weight: 100
  editorHidden: true

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  weight: -94
  primary: false
  editorHidden: true

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  weight: -93
  editorHidden: true

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  editorHidden: true

- type: department
  id: Epistemics
  description: department-Epistemics-description
  color: "#D381C9"
  weight: -92
  primary: false
  editorHidden: true

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: -91
  primary: false
  editorHidden: true

- type: department
  id: FAC1
  description: department-FAC1-description
  color: "#775a20"
  weight: 100
  editorHidden: false

- type: department
  id: FAC2
  description: department-FAC2-description
  color: "#28918d"
  weight: 90
  editorHidden: false

- type: department
  id: FAC3
  description: department-FAC3-description
  color: "#8a0d26"
  weight: 90
  editorHidden: false
